#!/usr/bin/env bun
// Generates model-hint modules from the committed snapshot (ADR-0028).
// --refresh first fetches models.dev and updates that snapshot; normal generation
// is deterministic and offline. Codex hints stay hand-maintained in the provider.
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { knownModelIds as codexIds } from "../packages/providers/src/openai-codex/models.ts";

const root = fileURLToPath(new URL("..", import.meta.url));
const snapshotPath = join(root, "scripts", "models-dev.snapshot.json");
const openAiHintsPath = join(root, "packages", "providers", "src", "openai", "models.ts");
const createMitomeHintsPath = join(root, "packages", "create-mitome", "src", "model-hints.ts");

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

const toolCapableOpenAiIds = (payload: unknown): Array<string> => {
  const models = isRecord(payload) && isRecord(payload.openai) ? payload.openai.models : undefined;
  return isRecord(models)
    ? Object.values(models).flatMap((model) =>
        isRecord(model) &&
        typeof model.id === "string" &&
        model.id !== "" &&
        model.tool_call === true
          ? [model.id]
          : [],
      )
    : [];
};

const fetchOpenAiIds = async (): Promise<Array<string>> => {
  const response = await fetch("https://models.dev/api.json", {
    signal: AbortSignal.timeout(10_000),
  });
  if (!response.ok) throw new Error(`models.dev returned ${response.status}`);
  const ids = toolCapableOpenAiIds(await response.json());
  if (ids.length === 0) throw new Error("models.dev returned no tool-capable OpenAI models");
  // Descending sort keeps newest model generations first and diffs deterministic.
  return ids.sort((left, right) => (left < right ? 1 : -1));
};

const snapshotOpenAiIds = async (): Promise<Array<string>> => {
  const snapshot: unknown = JSON.parse(await readFile(snapshotPath, "utf8"));
  const ids =
    isRecord(snapshot) && Array.isArray(snapshot.openai)
      ? snapshot.openai.filter((id): id is string => typeof id === "string" && id !== "")
      : [];
  if (ids.length === 0) throw new Error(`Snapshot ${snapshotPath} holds no OpenAI ids.`);
  return ids;
};

const args = process.argv.slice(2);
if (args.length > 1 || (args.length === 1 && args[0] !== "--refresh")) {
  throw new Error("Usage: generate-model-hints.ts [--refresh]");
}

const openAiIds =
  args[0] === "--refresh"
    ? await fetchOpenAiIds().then(async (ids) => {
        await writeFile(snapshotPath, `${JSON.stringify({ openai: ids }, null, 2)}\n`);
        return ids;
      })
    : await snapshotOpenAiIds();

const header = "// Generated by scripts/generate-model-hints.ts — do not edit.";
const items = (ids: ReadonlyArray<string>, indent: string): string =>
  ids.map((id) => `${indent}"${id}",`).join("\n");

await writeFile(
  openAiHintsPath,
  `${header}
export const knownModelIds = [
${items(openAiIds, "  ")}
] as const;

export type KnownModelId = (typeof knownModelIds)[number];
`,
);

await writeFile(
  createMitomeHintsPath,
  `${header}
export const knownModelIds: {
  readonly openai: ReadonlyArray<string>;
  readonly "openai-codex": ReadonlyArray<string>;
} = {
  openai: [
${items(openAiIds, "    ")}
  ],
  "openai-codex": [
${items(codexIds, "    ")}
  ],
};
`,
);

console.log(`Generated model hints: ${openAiIds.length} OpenAI ids, ${codexIds.length} Codex ids.`);
