#!/usr/bin/env bun
// Generates the model-hint modules from models.dev (ADR-0028). OpenAI hints are
// tool-capable models.dev ids; Codex hints stay hand-maintained in the provider
// (the ChatGPT backend has no discovery API). A successful fetch refreshes the
// committed snapshot; a failed fetch emits from the snapshot with a warning.
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const snapshotPath = join(root, "scripts", "models-dev.snapshot.json");
const openAiHintsPath = join(root, "packages", "providers", "src", "openai", "models.ts");
const codexHintsPath = join(root, "packages", "providers", "src", "openai-codex", "models.ts");
const createMitomeHintsPath = join(root, "packages", "create-mitome", "src", "model-hints.ts");

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

const toolCapableOpenAiIds = (payload: unknown): Array<string> => {
  const models = isRecord(payload) && isRecord(payload.openai) ? payload.openai.models : undefined;
  return isRecord(models)
    ? Object.values(models).flatMap((model) =>
        isRecord(model) &&
        typeof model.id === "string" &&
        model.id !== "" &&
        model.tool_call === true
          ? [model.id]
          : [],
      )
    : [];
};

const fetchOpenAiIds = async (): Promise<Array<string>> => {
  const response = await fetch("https://models.dev/api.json", {
    signal: AbortSignal.timeout(10_000),
  });
  if (!response.ok) throw new Error(`models.dev returned ${response.status}`);
  const ids = toolCapableOpenAiIds(await response.json());
  if (ids.length === 0) throw new Error("models.dev returned no tool-capable OpenAI models");
  // Descending sort keeps newest model generations first and diffs deterministic.
  return ids.sort((left, right) => (left < right ? 1 : -1));
};

const snapshotOpenAiIds = async (cause: unknown): Promise<Array<string>> => {
  let snapshot: unknown;
  try {
    snapshot = JSON.parse(await readFile(snapshotPath, "utf8"));
  } catch {
    throw new Error(
      `models.dev is unreachable and no snapshot exists at ${snapshotPath}; connect and retry.`,
      { cause },
    );
  }
  const ids =
    isRecord(snapshot) && Array.isArray(snapshot.openai)
      ? snapshot.openai.filter((id): id is string => typeof id === "string" && id !== "")
      : [];
  if (ids.length === 0) throw new Error(`Snapshot ${snapshotPath} holds no OpenAI ids.`, { cause });
  console.warn(
    `WARNING: models.dev fetch failed (${cause instanceof Error ? cause.message : String(cause)}); emitting model hints from the committed snapshot.`,
  );
  return ids;
};

const openAiIds = await fetchOpenAiIds().then(async (ids) => {
  await writeFile(snapshotPath, `${JSON.stringify({ openai: ids }, null, 2)}\n`);
  return ids;
}, snapshotOpenAiIds);

const codexSource = await readFile(codexHintsPath, "utf8");
const codexList = /knownModelIds = \[(?<items>[^\]]*)\]/.exec(codexSource)?.groups?.items;
const codexIds = [...(codexList ?? "").matchAll(/"(?<id>[^"]+)"/g)].map(
  (match) => match.groups!.id!,
);
if (codexIds.length === 0) {
  throw new Error(`Could not parse the hand-maintained Codex ids from ${codexHintsPath}.`);
}

const header = "// Generated by scripts/generate-model-hints.ts — do not edit.";
const items = (ids: ReadonlyArray<string>, indent: string): string =>
  ids.map((id) => `${indent}"${id}",`).join("\n");

await writeFile(
  openAiHintsPath,
  `${header}
export const knownModelIds = [
${items(openAiIds, "  ")}
] as const;

export type KnownModelId = (typeof knownModelIds)[number];
export type ModelId = KnownModelId | (string & {});
`,
);

await writeFile(
  createMitomeHintsPath,
  `${header}
export const knownModelIds: {
  readonly openai: ReadonlyArray<string>;
  readonly "openai-codex": ReadonlyArray<string>;
} = {
  openai: [
${items(openAiIds, "    ")}
  ],
  "openai-codex": [
${items(codexIds, "    ")}
  ],
};
`,
);

console.log(`Generated model hints: ${openAiIds.length} OpenAI ids, ${codexIds.length} Codex ids.`);
